blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/GeeekyBoy/Quine-McCluskey-Solver/discussions/categories/ideas
    about: Have an idea for a new feature? Let us know!
