on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

env:
  VITE_CANONICAL_URL: ${{ secrets.CANONICAL_URL }}
  VITE_GOOGLE_VERIFICATION: ${{ secrets.GOOGLE_VERIFICATION }}
  VITE_GTAG: ${{ secrets.GTAG }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        path: dist